apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    qcloud-app: fk-model-deploy
  name: fk-model-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      qcloud-app: fk-model-deploy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        qcloud-app: fk-model-deploy
    spec:
      initContainers:
      - name: setup
        image: ccr.ccs.tencentyun.com/kuainiu/fk-model:45dc61f6dbf24ed1c03fa31477820512516d6a20
        args: ["sh", "-c", "cp -rf /www/* /var/www/html"]
        imagePullPolicy: Always

      containers:
      - image: php:7.3.0-fpm-alpine3.8
        imagePullPolicy: Always
        name: fk-model-fpm-deploy

      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: qcloudregistrykey
        - name: tencenthubkey
      restartPolicy: Always

